// 把声明式 Block[] 渲染成 letter-size PDF。纯客户端，pdf-lib。
// pdf-lib 较重，动态 import，仅在生成时加载，不进首屏 bundle。
import type { PDFFont, PDFPage } from 'pdf-lib'
import type { WaiverData, WaiverTemplate } from './types'

const PAGE_W = 612
const PAGE_H = 792
const MARGIN = 54
const CONTENT_W = PAGE_W - MARGIN * 2
const FOOTER =
  'Generated by WaiverFlow. This is a format-rendering tool, not legal advice. Verify the form against current statute and consult an attorney.'

// 把一段文字按可用宽度拆成多行。
function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/)
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
      lines.push(line)
      line = word
    } else {
      line = candidate
    }
  }
  if (line) lines.push(line)
  return lines
}

// {{key}} 插值：有值填值，无值留法定下划线占位。
function interpolate(text: string, data: WaiverData): string {
  return text.replace(/\{\{(\w+)\}\}/g, (_, key: string) => data[key]?.trim() || '__________')
}

export async function generateWaiverPdf(template: WaiverTemplate, data: WaiverData): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib')
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  let page = doc.addPage([PAGE_W, PAGE_H])
  let y = PAGE_H - MARGIN

  const drawFooter = (p: PDFPage) => {
    const lines = wrapText(FOOTER, font, 7, CONTENT_W)
    let fy = 36
    for (const ln of lines.reverse()) {
      p.drawText(ln, { x: MARGIN, y: fy, size: 7, font, color: rgb(0.45, 0.45, 0.45) })
      fy -= 9
    }
  }

  const newPage = () => {
    drawFooter(page)
    page = doc.addPage([PAGE_W, PAGE_H])
    y = PAGE_H - MARGIN
  }

  const ensure = (needed: number) => {
    if (y - needed < MARGIN + 24) newPage()
  }

  const writeLines = (lines: string[], size: number, useFont: PDFFont, gap = 4, x = MARGIN) => {
    for (const ln of lines) {
      ensure(size + gap)
      page.drawText(ln, { x, y: y - size, size, font: useFont, color: rgb(0.1, 0.1, 0.1) })
      y -= size + gap
    }
  }

  for (const block of template.blocks) {
    switch (block.kind) {
      case 'title': {
        const lines = wrapText(block.text, bold, 13, CONTENT_W)
        for (const ln of lines) {
          ensure(18)
          const w = bold.widthOfTextAtSize(ln, 13)
          page.drawText(ln, { x: (PAGE_W - w) / 2, y: y - 13, size: 13, font: bold, color: rgb(0, 0, 0) })
          y -= 18
        }
        y -= 8
        break
      }
      case 'notice': {
        const lines = wrapText(block.text, bold, 8.5, CONTENT_W - 16)
        const boxH = lines.length * 12 + 16
        ensure(boxH + 8)
        page.drawRectangle({
          x: MARGIN,
          y: y - boxH,
          width: CONTENT_W,
          height: boxH,
          borderColor: rgb(0, 0, 0),
          borderWidth: 1.2,
        })
        let ny = y - 8
        for (const ln of lines) {
          page.drawText(ln, { x: MARGIN + 8, y: ny - 8.5, size: 8.5, font: bold, color: rgb(0, 0, 0) })
          ny -= 12
        }
        y -= boxH + 12
        break
      }
      case 'heading': {
        ensure(20)
        page.drawText(block.text, { x: MARGIN, y: y - 11, size: 11, font: bold, color: rgb(0, 0, 0) })
        y -= 18
        break
      }
      case 'paragraph': {
        const lines = wrapText(interpolate(block.text, data), font, 10, CONTENT_W)
        writeLines(lines, 10, font, 4)
        y -= 6
        break
      }
      case 'field': {
        const value = data[block.key]?.trim() || ''
        const shown = value ? `${block.prefix ?? ''}${value}` : '______________________________'
        ensure(16)
        const label = `${block.label}: `
        page.drawText(label, { x: MARGIN, y: y - 10, size: 10, font: bold, color: rgb(0.1, 0.1, 0.1) })
        const lw = bold.widthOfTextAtSize(label, 10)
        page.drawText(shown, { x: MARGIN + lw, y: y - 10, size: 10, font, color: rgb(0.1, 0.1, 0.1) })
        y -= 16
        break
      }
      case 'spacer':
        y -= 10
        break
    }
  }

  drawFooter(page)
  return doc.save()
}

// 把 PDF 字节包成 blob object URL，供 <iframe> 预览。
// 调用方负责在替换/卸载前 revokeObjectURL，否则内存泄漏。
export function pdfObjectUrl(bytes: Uint8Array): string {
  const blob = new Blob([bytes as BlobPart], { type: 'application/pdf' })
  return URL.createObjectURL(blob)
}

// 触发浏览器下载。即用即 revoke。
export function downloadPdf(bytes: Uint8Array, filename: string) {
  const url = pdfObjectUrl(bytes)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
